# Base de données complète des plantes avec variétés et données d'écartement premium
# 64 variétés avec toutes les spécifications techniques

PLANTS_DATABASE = [
    # TOMATES (10 variétés) - Écartement: 60-75cm entre pieds, 80-95cm entre rangées
    {
        "name_fr": "Tomate Cœur de Bœuf",
        "name_latin": "Solanum lycopersicum 'Cœur de Bœuf'",
        "variety": "Cœur de Bœuf",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Coeur_de_boeuf_vraie.JPG/800px-Coeur_de_boeuf_vraie.JPG",
        "description": "Grosse tomate charnue en forme de cœur, très savoureuse",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil (8h minimum)",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 3-4 fois par semaine",
        "spacing_between_plants": "70 cm",
        "spacing_between_rows": "90 cm"
    },
    {
        "name_fr": "Tomate Marmande",
        "name_latin": "Solanum lycopersicum 'Marmande'",
        "variety": "Marmande",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Tomates_Marmande.jpg/1280px-Tomates_Marmande.jpg",
        "description": "Tomate côtelée, chair ferme, parfaite pour les salades",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré régulier",
        "soil_type": "Sol riche en humus",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "70 cm",
        "spacing_between_rows": "90 cm"
    },
    {
        "name_fr": "Tomate Cerise",
        "name_latin": "Solanum lycopersicum 'Cherry'",
        "variety": "Cerise",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tomates_cerises_Luc_Viatour.jpg/640px-Tomates_cerises_Luc_Viatour.jpg",
        "description": "Petites tomates sucrées, très productives",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine",
        "spacing_between_plants": "60 cm",
        "spacing_between_rows": "80 cm"
    },
    {
        "name_fr": "Tomate Roma",
        "name_latin": "Solanum lycopersicum 'Roma'",
        "variety": "Roma",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Roma_tomatoes.jpg/1280px-Roma_tomatoes.jpg",
        "description": "Tomate allongée parfaite pour les sauces",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage au pied",
        "soil_type": "Sol drainé",
        "monthly_watering": "Juin: 3 fois par semaine",
        "spacing_between_plants": "65 cm",
        "spacing_between_rows": "85 cm"
    },
    {
        "name_fr": "Tomate Noire de Crimée",
        "name_latin": "Solanum lycopersicum 'Black Krim'",
        "variety": "Noire de Crimée",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Cherokee_purple_tomato.jpg/1280px-Cherokee_purple_tomato.jpg",
        "description": "Tomate ancienne à la couleur pourpre-noire unique",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "75 cm",
        "spacing_between_rows": "95 cm"
    },
    {
        "name_fr": "Tomate Cornu des Andes",
        "name_latin": "Solanum lycopersicum 'Cornue des Andes'",
        "variety": "Cornu des Andes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cornue_des_andes_tomato.jpg/1280px-Cornue_des_andes_tomato.jpg",
        "description": "Tomate allongée en forme de corne, très charnue",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol profond et riche",
        "monthly_watering": "Juin: 3-4 fois par semaine",
        "spacing_between_plants": "70 cm",
        "spacing_between_rows": "90 cm"
    },
    {
        "name_fr": "Tomate Buffalo",
        "name_latin": "Solanum lycopersicum 'Buffalo'",
        "variety": "Buffalo",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Beef_tomato.jpg/1280px-Beef_tomato.jpg",
        "description": "Grosse tomate charnue, idéale pour les salades",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage au pied",
        "soil_type": "Sol bien amendé",
        "monthly_watering": "Juin: 3 fois par semaine",
        "spacing_between_plants": "75 cm",
        "spacing_between_rows": "95 cm"
    },
    {
        "name_fr": "Tomate Ananas",
        "name_latin": "Solanum lycopersicum 'Ananas'",
        "variety": "Ananas",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Pineapple_tomato.jpg/1280px-Pineapple_tomato.jpg",
        "description": "Tomate bicolore jaune et rouge, très parfumée",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol fertile",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "70 cm",
        "spacing_between_rows": "90 cm"
    },
    {
        "name_fr": "Tomate Saint-Pierre",
        "name_latin": "Solanum lycopersicum 'Saint-Pierre'",
        "variety": "Saint-Pierre",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tomato_Saint_Pierre.jpg/1280px-Tomato_Saint_Pierre.jpg",
        "description": "Variété française traditionnelle, très productive",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol ordinaire bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine",
        "spacing_between_plants": "65 cm",
        "spacing_between_rows": "85 cm"
    },
    {
        "name_fr": "Tomate Green Zebra",
        "name_latin": "Solanum lycopersicum 'Green Zebra'",
        "variety": "Green Zebra",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Green_zebra_tomato.jpg/1280px-Green_zebra_tomato.jpg",
        "description": "Tomate verte striée de jaune, saveur acidulée",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage au pied",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "65 cm",
        "spacing_between_rows": "85 cm"
    },

    # CAROTTES (2 variétés) - Écartement: 5cm entre pieds, 25-30cm entre rangées
    {
        "name_fr": "Carotte de Nantes",
        "name_latin": "Daucus carota 'Nantes'",
        "variety": "de Nantes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Carrot_Nantes.jpg/1280px-Carrot_Nantes.jpg",
        "description": "Carotte demi-longue, très tendre et sucrée",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil à mi-ombre",
        "watering": "Arrosage régulier léger",
        "soil_type": "Sol meuble et profond",
        "monthly_watering": "Juillet: 2 fois par semaine",
        "spacing_between_plants": "5 cm",
        "spacing_between_rows": "25 cm"
    },
    {
        "name_fr": "Carotte de Colmar",
        "name_latin": "Daucus carota 'Colmar à cœur rouge'",
        "variety": "de Colmar",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Carotte_Colmar.jpg/1280px-Carotte_Colmar.jpg",
        "description": "Carotte longue à cœur rouge, excellente conservation",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol profond sans cailloux",
        "monthly_watering": "Juillet: 2 fois par semaine",
        "spacing_between_plants": "5 cm",
        "spacing_between_rows": "30 cm"
    },

    # SALADES (9 variétés) - Écartement: 15-30cm entre pieds, 20-35cm entre rangées
    {
        "name_fr": "Batavia Blonde",
        "name_latin": "Lactuca sativa 'Batavia Blonde'",
        "variety": "Batavia Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Batavia_lettuce.jpg/1280px-Batavia_lettuce.jpg",
        "description": "Salade croquante aux feuilles blondes et épaisses",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre en été, soleil au printemps",
        "watering": "Arrosage fréquent léger",
        "soil_type": "Sol frais et riche",
        "monthly_watering": "Juin: 4-5 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Batavia Rouge",
        "name_latin": "Lactuca sativa 'Batavia Rouge'",
        "variety": "Batavia Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Red_batavia_lettuce.jpg/1280px-Red_batavia_lettuce.jpg",
        "description": "Salade aux feuilles rouges, très décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol humifère",
        "monthly_watering": "Juin: 4-5 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Romaine",
        "name_latin": "Lactuca sativa 'Romaine'",
        "variety": "Romaine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Romaine_lettuce.jpg/1280px-Romaine_lettuce.jpg",
        "description": "Salade aux feuilles allongées, très croquante",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage au pied",
        "soil_type": "Sol fertile et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine",
        "spacing_between_plants": "30 cm",
        "spacing_between_rows": "35 cm"
    },
    {
        "name_fr": "Feuille de Chêne Blonde",
        "name_latin": "Lactuca sativa 'Feuille de chêne blonde'",
        "variety": "Feuille de Chêne Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Oak_leaf_lettuce_blonde.jpg/1280px-Oak_leaf_lettuce_blonde.jpg",
        "description": "Salade aux feuilles découpées, très tendre",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage doux et régulier",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Juin: 4 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Feuille de Chêne Rouge",
        "name_latin": "Lactuca sativa 'Feuille de chêne rouge'",
        "variety": "Feuille de Chêne Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Red_oak_leaf_lettuce.jpg/1280px-Red_oak_leaf_lettuce.jpg",
        "description": "Salade rouge aux feuilles découpées",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage au pied",
        "soil_type": "Sol riche en matière organique",
        "monthly_watering": "Juin: 4 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Lollo Rossa",
        "name_latin": "Lactuca sativa 'Lollo Rossa'",
        "variety": "Lollo Rossa",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Lollo_Rosso_lettuce.jpg/1280px-Lollo_Rosso_lettuce.jpg",
        "description": "Salade italienne aux feuilles très frisées",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage léger quotidien",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 5 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Iceberg",
        "name_latin": "Lactuca sativa 'Iceberg'",
        "variety": "Iceberg",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Iceberg_lettuce.jpg/1280px-Iceberg_lettuce.jpg",
        "description": "Salade pommée très croquante et rafraîchissante",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 3-4 fois par semaine",
        "spacing_between_plants": "30 cm",
        "spacing_between_rows": "35 cm"
    },
    {
        "name_fr": "Sucrine",
        "name_latin": "Lactuca sativa 'Sucrine'",
        "variety": "Sucrine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Sucrine_lettuce.jpg/1280px-Sucrine_lettuce.jpg",
        "description": "Petite salade sucrée, parfaite en une portion",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage doux",
        "soil_type": "Sol fertile",
        "monthly_watering": "Juin: 4 fois par semaine",
        "spacing_between_plants": "20 cm",
        "spacing_between_rows": "25 cm"
    },
    {
        "name_fr": "Roquette",
        "name_latin": "Eruca vesicaria",
        "variety": "Cultivée",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Eruca_vesicaria_Rocket.jpg/1280px-Eruca_vesicaria_Rocket.jpg",
        "description": "Salade au goût piquant et poivré",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage fréquent léger",
        "soil_type": "Sol ordinaire",
        "monthly_watering": "Juin: 4-5 fois par semaine",
        "spacing_between_plants": "15 cm",
        "spacing_between_rows": "20 cm"
    },

    # COURGETTES (2 variétés) - Écartement: 100cm entre pieds, 120cm entre rangées
    {
        "name_fr": "Courgette Verte",
        "name_latin": "Cucurbita pepo",
        "variety": "Verte de Milan",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Courgette_verte.jpg/1280px-Courgette_verte.jpg",
        "description": "Courgette verte classique, très productive",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage copieux au pied",
        "soil_type": "Sol riche et bien fumé",
        "monthly_watering": "Juillet: 3-4 fois par semaine",
        "spacing_between_plants": "100 cm",
        "spacing_between_rows": "120 cm"
    },
    {
        "name_fr": "Courgette Ronde de Nice",
        "name_latin": "Cucurbita pepo 'Ronde de Nice'",
        "variety": "Ronde de Nice",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Courgette_ronde_de_Nice.jpg/1280px-Courgette_ronde_de_Nice.jpg",
        "description": "Courgette ronde traditionnelle de Nice, parfaite à farcir",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier abondant",
        "soil_type": "Sol profond et riche",
        "monthly_watering": "Juillet: 3-4 fois par semaine",
        "spacing_between_plants": "100 cm",
        "spacing_between_rows": "120 cm"
    },

    # RADIS (2 variétés) - Écartement: 3-8cm entre pieds, 15-20cm entre rangées
    {
        "name_fr": "Radis 18 Jours",
        "name_latin": "Raphanus sativus '18 jours'",
        "variety": "18 Jours",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Radis_18_jours.jpg/1280px-Radis_18_jours.jpg",
        "description": "Radis rouge et blanc, croissance très rapide",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage quotidien léger",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Mai: quotidien",
        "spacing_between_plants": "3 cm",
        "spacing_between_rows": "15 cm"
    },
    {
        "name_fr": "Radis Noir",
        "name_latin": "Raphanus sativus 'Niger'",
        "variety": "Noir",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Black_radish.jpg/1280px-Black_radish.jpg",
        "description": "Radis noir d'hiver, chair blanche et piquante",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol profond et meuble",
        "monthly_watering": "Septembre: 2-3 fois par semaine",
        "spacing_between_plants": "8 cm",
        "spacing_between_rows": "20 cm"
    },

    # FRAISES (3 variétés) - Écartement: 35cm entre pieds, 50cm entre rangées
    {
        "name_fr": "Fraise Mara des Bois",
        "name_latin": "Fragaria × ananassa 'Mara des Bois'",
        "variety": "Mara des Bois",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Mara_des_bois_strawberry.jpg/1280px-Mara_des_bois_strawberry.jpg",
        "description": "Fraise remontante au goût de fraise des bois",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "35 cm",
        "spacing_between_rows": "50 cm"
    },
    {
        "name_fr": "Fraise Gariguette",
        "name_latin": "Fragaria × ananassa 'Gariguette'",
        "variety": "Gariguette",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Gariguette_strawberry.jpg/1280px-Gariguette_strawberry.jpg",
        "description": "Fraise précoce très parfumée et sucrée",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage au pied sans mouiller les feuilles",
        "soil_type": "Sol léger et humifère",
        "monthly_watering": "Mai: 2-3 fois par semaine",
        "spacing_between_plants": "35 cm",
        "spacing_between_rows": "50 cm"
    },
    {
        "name_fr": "Fraise Charlotte",
        "name_latin": "Fragaria × ananassa 'Charlotte'",
        "variety": "Charlotte",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Charlotte_strawberry.jpg/1280px-Charlotte_strawberry.jpg",
        "description": "Fraise remontante très productive",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage modéré régulier",
        "soil_type": "Sol fertile et frais",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "35 cm",
        "spacing_between_rows": "50 cm"
    },

    # FRAMBOISES (2 variétés) - Écartement: 80cm entre pieds, 150cm entre rangées
    {
        "name_fr": "Framboise Meeker",
        "name_latin": "Rubus idaeus 'Meeker'",
        "variety": "Meeker",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Raspberries_Meeker.jpg/1280px-Raspberries_Meeker.jpg",
        "description": "Framboise rouge non remontante, très productive",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier en été",
        "soil_type": "Sol frais et humifère",
        "monthly_watering": "Juillet: 2-3 fois par semaine",
        "spacing_between_plants": "80 cm",
        "spacing_between_rows": "150 cm"
    },
    {
        "name_fr": "Framboise Autumn Bliss",
        "name_latin": "Rubus idaeus 'Autumn Bliss'",
        "variety": "Autumn Bliss",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Autumn_Bliss_raspberry.jpg/1280px-Autumn_Bliss_raspberry.jpg",
        "description": "Framboise remontante, récolte jusqu'en automne",
        "difficulty": "Moyen",
        "growing_season": ["été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage au pied",
        "soil_type": "Sol bien drainé et riche",
        "monthly_watering": "Août: 2 fois par semaine",
        "spacing_between_plants": "80 cm",
        "spacing_between_rows": "150 cm"
    },

    # HERBES AROMATIQUES (14 variétés) - Écartements variables selon la plante
    {
        "name_fr": "Basilic Genovese",
        "name_latin": "Ocimum basilicum 'Genovese'",
        "variety": "Genovese",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Basil-Basilico-Ocimum_basilicum-albahaca.jpg/1280px-Basil-Basilico-Ocimum_basilicum-albahaca.jpg",
        "description": "Basilic italien classique, parfait pour le pesto",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier sans mouiller les feuilles",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 3-4 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Basilic Pourpre",
        "name_latin": "Ocimum basilicum 'Purple Ruffles'",
        "variety": "Pourpre",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Purple_basil.jpg/1280px-Purple_basil.jpg",
        "description": "Basilic décoratif aux feuilles pourpres",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol léger et fertile",
        "monthly_watering": "Juin: 3 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Persil Plat",
        "name_latin": "Petroselinum crispum 'Neapolitanum'",
        "variety": "Plat",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Petroselinum_crispum_Flat_Leaf.jpg/1280px-Petroselinum_crispum_Flat_Leaf.jpg",
        "description": "Persil à feuilles plates, très aromatique",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol frais et humifère",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "15 cm",
        "spacing_between_rows": "25 cm"
    },
    {
        "name_fr": "Persil Frisé",
        "name_latin": "Petroselinum crispum 'Crispum'",
        "variety": "Frisé",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Parsley_curly.jpg/1280px-Parsley_curly.jpg",
        "description": "Persil traditionnel aux feuilles frisées",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage au pied",
        "soil_type": "Sol fertile et frais",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "15 cm",
        "spacing_between_rows": "25 cm"
    },
    {
        "name_fr": "Ciboulette",
        "name_latin": "Allium schoenoprasum",
        "variety": "Commune",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Allium_schoenoprasum_LC0119.jpg/1280px-Allium_schoenoprasum_LC0119.jpg",
        "description": "Herbe vivace au goût d'oignon doux",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol ordinaire bien drainé",
        "monthly_watering": "Juin: 2 fois par semaine",
        "spacing_between_plants": "10 cm",
        "spacing_between_rows": "20 cm"
    },
    {
        "name_fr": "Thym Commun",
        "name_latin": "Thymus vulgaris",
        "variety": "Commun",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Thymus_vulgaris_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-019.jpg/1280px-Thymus_vulgaris_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-019.jpg",
        "description": "Plante vivace méditerranéenne très aromatique",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage parcimonieux",
        "soil_type": "Sol sec et drainant",
        "monthly_watering": "Juin: 1 fois par semaine",
        "spacing_between_plants": "30 cm",
        "spacing_between_rows": "40 cm"
    },
    {
        "name_fr": "Romarin",
        "name_latin": "Rosmarinus officinalis",
        "variety": "Officinal",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Rosmarinus_officinalis_003.JPG/1280px-Rosmarinus_officinalis_003.JPG",
        "description": "Arbuste persistant aux feuilles en aiguilles",
        "difficulty": "Facile",
        "growing_season": ["toute l'année"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage très parcimonieux",
        "soil_type": "Sol sec et calcaire",
        "monthly_watering": "Juin: 1 fois tous les 15 jours",
        "spacing_between_plants": "60 cm",
        "spacing_between_rows": "80 cm"
    },
    {
        "name_fr": "Lavande",
        "name_latin": "Lavandula angustifolia",
        "variety": "Vraie",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Single_lavendar_flower02.jpg/1280px-Single_lavendar_flower02.jpg",
        "description": "Plante vivace aux fleurs parfumées",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage rare",
        "soil_type": "Sol pauvre et drainé",
        "monthly_watering": "Juin: 1 fois par semaine",
        "spacing_between_plants": "50 cm",
        "spacing_between_rows": "70 cm"
    },
    {
        "name_fr": "Menthe Verte",
        "name_latin": "Mentha spicata",
        "variety": "Verte",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Mentha_spicata_003.JPG/1280px-Mentha_spicata_003.JPG",
        "description": "Menthe classique très rafraîchissante",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage copieux et régulier",
        "soil_type": "Sol humide et riche",
        "monthly_watering": "Juin: 4-5 fois par semaine",
        "spacing_between_plants": "30 cm",
        "spacing_between_rows": "40 cm"
    },
    {
        "name_fr": "Menthe Poivrée",
        "name_latin": "Mentha × piperita",
        "variety": "Poivrée",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Mentha_piperita_002.JPG/1280px-Mentha_piperita_002.JPG",
        "description": "Menthe hybride au goût intense et frais",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage abondant",
        "soil_type": "Sol frais et fertile",
        "monthly_watering": "Juin: 4-5 fois par semaine",
        "spacing_between_plants": "30 cm",
        "spacing_between_rows": "40 cm"
    },
    {
        "name_fr": "Origan",
        "name_latin": "Origanum vulgare",
        "variety": "Commun",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Origanum_vulgare_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-017.jpg/1280px-Origanum_vulgare_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-017.jpg",
        "description": "Herbe vivace indispensable à la cuisine méditerranéenne",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol drainé et léger",
        "monthly_watering": "Juin: 2 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "35 cm"
    },
    {
        "name_fr": "Sauge Officinale",
        "name_latin": "Salvia officinalis",
        "variety": "Officinale",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Salvia_officinalis_003.JPG/1280px-Salvia_officinalis_003.JPG",
        "description": "Plante vivace aux propriétés médicinales",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage parcimonieux",
        "soil_type": "Sol sec et calcaire",
        "monthly_watering": "Juin: 1-2 fois par semaine",
        "spacing_between_plants": "40 cm",
        "spacing_between_rows": "50 cm"
    },
    {
        "name_fr": "Coriandre",
        "name_latin": "Coriandrum sativum",
        "variety": "Cultivée",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/A_scene_of_Coriander_leaves.jpg/1280px-A_scene_of_Coriander_leaves.jpg",
        "description": "Herbe annuelle au goût caractéristique",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier léger",
        "soil_type": "Sol frais et fertile",
        "monthly_watering": "Juin: 3 fois par semaine",
        "spacing_between_plants": "15 cm",
        "spacing_between_rows": "25 cm"
    },
    {
        "name_fr": "Aneth",
        "name_latin": "Anethum graveolens",
        "variety": "Commun",
        "category": "potager",
        "subcategory": "herbes_aromatiques",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Anethum_graveolens_003.JPG/1280px-Anethum_graveolens_003.JPG",
        "description": "Plante annuelle aux feuilles filiformes",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage modéré régulier",
        "soil_type": "Sol léger et bien drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "20 cm",
        "spacing_between_rows": "30 cm"
    },

    # PETITS FRUITS (4 variétés) - Écartements pour arbustes
    {
        "name_fr": "Cassis",
        "name_latin": "Ribes nigrum",
        "variety": "Noir de Bourgogne",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Ribes_nigrum_003.JPG/1280px-Ribes_nigrum_003.JPG",
        "description": "Arbuste produisant des baies noires riches en vitamine C",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier en été",
        "soil_type": "Sol frais et humifère",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "120 cm",
        "spacing_between_rows": "200 cm"
    },
    {
        "name_fr": "Groseillier Rouge",
        "name_latin": "Ribes rubrum",
        "variety": "Rouge de Hollande",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Ribes_rubrum_003.JPG/1280px-Ribes_rubrum_003.JPG",
        "description": "Arbuste aux grappes de petites baies rouges acidulées",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 2 fois par semaine",
        "spacing_between_plants": "120 cm",
        "spacing_between_rows": "200 cm"
    },
    {
        "name_fr": "Groseillier à Maquereaux",
        "name_latin": "Ribes uva-crispa",
        "variety": "Variabilis",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Ribes_uva-crispa_004.JPG/1280px-Ribes_uva-crispa_004.JPG",
        "description": "Arbuste épineux aux gros fruits verts ou rouges",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage au pied",
        "soil_type": "Sol fertile et drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "120 cm",
        "spacing_between_rows": "200 cm"
    },
    {
        "name_fr": "Myrtille",
        "name_latin": "Vaccinium corymbosum",
        "variety": "Arbustive",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Vaccinium_corymbosum_003.JPG/1280px-Vaccinium_corymbosum_003.JPG",
        "description": "Arbuste acidophile aux baies bleues antioxydantes",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage à l'eau douce",
        "soil_type": "Sol acide et humifère",
        "monthly_watering": "Juin: 3-4 fois par semaine",
        "spacing_between_plants": "100 cm",
        "spacing_between_rows": "150 cm"
    },

    # ARBRES FRUITIERS (10 variétés) - Écartements pour vergers
    {
        "name_fr": "Cerise",
        "name_latin": "Prunus avium",
        "variety": "Burlat",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Cherry_tree_blossoms_closeup.jpg/1280px-Cherry_tree_blossoms_closeup.jpg",
        "description": "Arbre fruitier aux fleurs blanches et fruits rouge foncé",
        "difficulty": "Moyen",
        "growing_season": ["printemps"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage en cas de sécheresse",
        "soil_type": "Sol profond et bien drainé",
        "monthly_watering": "Juin: selon besoin",
        "spacing_between_plants": "400 cm",
        "spacing_between_rows": "500 cm"
    },
    {
        "name_fr": "Pomme",
        "name_latin": "Malus domestica",
        "variety": "Golden Delicious",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/1280px-Red_Apple.jpg",
        "description": "Arbre fruitier classique aux multiples variétés",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol fertile et profond",
        "monthly_watering": "Juin: 1-2 fois par semaine",
        "spacing_between_plants": "400 cm",
        "spacing_between_rows": "500 cm"
    },
    {
        "name_fr": "Poire",
        "name_latin": "Pyrus communis",
        "variety": "Williams",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Pears_grow_on_tree.jpg/1280px-Pears_grow_on_tree.jpg",
        "description": "Arbre fruitier aux fruits juteux et parfumés",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier jeune plant",
        "soil_type": "Sol profond et frais",
        "monthly_watering": "Juin: 1-2 fois par semaine",
        "spacing_between_plants": "350 cm",
        "spacing_between_rows": "450 cm"
    },
    {
        "name_fr": "Pêche",
        "name_latin": "Prunus persica",
        "variety": "Elberta",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Autumn_Red_peaches.jpg/1280px-Autumn_Red_peaches.jpg",
        "description": "Arbre fruitier méditerranéen aux fruits duveteux",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil abrité",
        "watering": "Arrosage copieux en été",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "400 cm",
        "spacing_between_rows": "500 cm"
    },
    {
        "name_fr": "Prune",
        "name_latin": "Prunus domestica",
        "variety": "Reine-Claude",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Plums_on_tree.jpg/1280px-Plums_on_tree.jpg",
        "description": "Arbre fruitier robuste aux fruits sucrés",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol ordinaire bien drainé",
        "monthly_watering": "Juin: 1-2 fois par semaine",
        "spacing_between_plants": "350 cm",
        "spacing_between_rows": "450 cm"
    },
    {
        "name_fr": "Abricot",
        "name_latin": "Prunus armeniaca",
        "variety": "Bergeron",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Apricots_on_tree.jpg/1280px-Apricots_on_tree.jpg",
        "description": "Arbre fruitier précoce aux fruits orange parfumés",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil protégé",
        "watering": "Arrosage parcimonieux",
        "soil_type": "Sol drainé et calcaire",
        "monthly_watering": "Juin: 1-2 fois par semaine",
        "spacing_between_plants": "400 cm",
        "spacing_between_rows": "500 cm"
    },
    {
        "name_fr": "Figue",
        "name_latin": "Ficus carica",
        "variety": "Violette de Bordeaux",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Figs_on_tree.jpg/1280px-Figs_on_tree.jpg",
        "description": "Arbre méditerranéen aux fruits sucrés",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage rare une fois établi",
        "soil_type": "Sol sec et drainé",
        "monthly_watering": "Juin: 1 fois par semaine",
        "spacing_between_plants": "300 cm",
        "spacing_between_rows": "400 cm"
    },
    {
        "name_fr": "Raisin",
        "name_latin": "Vitis vinifera",
        "variety": "Chasselas",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Grapes_on_vine.jpg/1280px-Grapes_on_vine.jpg",
        "description": "Vigne grimpante aux grappes de raisins",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien drainé et caillouteux",
        "monthly_watering": "Juin: 1-2 fois par semaine",
        "spacing_between_plants": "120 cm",
        "spacing_between_rows": "200 cm"
    },
    {
        "name_fr": "Kiwi",
        "name_latin": "Actinidia deliciosa",
        "variety": "Hayward",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kiwi_aka.jpg/1280px-Kiwi_aka.jpg",
        "description": "Liane vigoureuse aux fruits verts et poilus",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage copieux en été",
        "soil_type": "Sol frais et humifère",
        "monthly_watering": "Juin: 3-4 fois par semaine",
        "spacing_between_plants": "300 cm",
        "spacing_between_rows": "400 cm"
    },

    # AGRUMES (2 variétés) - Écartements pour climat méditerranéen ou serre
    {
        "name_fr": "Citronnier",
        "name_latin": "Citrus limon",
        "variety": "Eureka",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Lemon_tree_02.jpg/1280px-Lemon_tree_02.jpg",
        "description": "Arbre à agrumes produisant des citrons toute l'année",
        "difficulty": "Difficile",
        "growing_season": ["toute l'année"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier sans excès",
        "soil_type": "Sol drainé et légèrement acide",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "400 cm",
        "spacing_between_rows": "500 cm"
    },
    {
        "name_fr": "Oranger",
        "name_latin": "Citrus sinensis",
        "variety": "Naveline",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Ambersweet_oranges.jpg/1280px-Ambersweet_oranges.jpg",
        "description": "Arbre à agrumes aux fruits orange sucrés",
        "difficulty": "Difficile",
        "growing_season": ["toute l'année"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré et régulier",
        "soil_type": "Sol fertile et bien drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine",
        "spacing_between_plants": "400 cm",
        "spacing_between_rows": "500 cm"
    },

    # LÉGUMES RACINES ET FEUILLES (5 variétés) - Écartements variables
    {
        "name_fr": "Betterave Rouge",
        "name_latin": "Beta vulgaris",
        "variety": "Crapaudine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Beetroot_jm26647.jpg/1280px-Beetroot_jm26647.jpg",
        "description": "Légume racine à la chair rouge intense",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol profond et riche",
        "monthly_watering": "Juillet: 2-3 fois par semaine",
        "spacing_between_plants": "10 cm",
        "spacing_between_rows": "30 cm"
    },
    {
        "name_fr": "Céleri Branche",
        "name_latin": "Apium graveolens",
        "variety": "A côtes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Apium_graveolens_003.JPG/1280px-Apium_graveolens_003.JPG",
        "description": "Légume aux tiges croquantes et parfumées",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage copieux et régulier",
        "soil_type": "Sol riche et humide",
        "monthly_watering": "Juillet: 4-5 fois par semaine",
        "spacing_between_plants": "25 cm",
        "spacing_between_rows": "40 cm"
    },
    {
        "name_fr": "Fenouil Bulbeux",
        "name_latin": "Foeniculum vulgare",
        "variety": "De Florence",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Fennel_bulb.jpg/1280px-Fennel_bulb.jpg",
        "description": "Légume au goût anisé avec un bulbe charnu",
        "difficulty": "Moyen",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol fertile et frais",
        "monthly_watering": "Août: 3-4 fois par semaine",
        "spacing_between_plants": "30 cm",
        "spacing_between_rows": "40 cm"
    },
    {
        "name_fr": "Épinard",
        "name_latin": "Spinacia oleracea",
        "variety": "Géant d'hiver",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Spinach_leaves.jpg/1280px-Spinach_leaves.jpg",
        "description": "Légume feuille riche en fer et vitamines",
        "difficulty": "Facile",
        "growing_season": ["printemps", "automne", "hiver"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage fréquent léger",
        "soil_type": "Sol riche en azote",
        "monthly_watering": "Octobre: 3-4 fois par semaine",
        "spacing_between_plants": "15 cm",
        "spacing_between_rows": "25 cm"
    },
    {
        "name_fr": "Mâche",
        "name_latin": "Valerianella locusta",
        "variety": "Verte de Cambrai",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Valerianella_locusta_003.JPG/1280px-Valerianella_locusta_003.JPG",
        "description": "Salade d'hiver aux petites feuilles tendres",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage léger",
        "soil_type": "Sol ordinaire",
        "monthly_watering": "Novembre: 1-2 fois par semaine",
        "spacing_between_plants": "10 cm",
        "spacing_between_rows": "20 cm"
    }
]