# Base de données complète des plantes avec variétés - URLs Wikipedia Commons
# 37 variétés avec photos génériques temporaires

PLANTS_DATABASE = [
    # TOMATES (10 variétés) - Photo générique tomates rouges
    {
        "name_fr": "Tomate Cœur de Bœuf",
        "name_latin": "Solanum lycopersicum 'Cœur de Bœuf'",
        "variety": "Cœur de Bœuf",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Coeur_de_boeuf_vraie.JPG/800px-Coeur_de_boeuf_vraie.JPG",
        "description": "Grosse tomate charnue en forme de cœur, très savoureuse",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil (8h minimum)",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Marmande",
        "name_latin": "Solanum lycopersicum 'Marmande'",
        "variety": "Marmande",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Tomates_Marmande.jpg/1280px-Tomates_Marmande.jpg",
        "description": "Tomate côtelée, chair ferme, parfaite pour les salades",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré régulier",
        "soil_type": "Sol riche en humus",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Tomate Cerise",
        "name_latin": "Solanum lycopersicum 'Cherry'",
        "variety": "Cerise",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tomates_cerises_Luc_Viatour.jpg/640px-Tomates_cerises_Luc_Viatour.jpg",
        "description": "Petites tomates sucrées, très productives",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Roma",
        "name_latin": "Solanum lycopersicum 'Roma'",
        "variety": "Roma",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Roma_tomatoes.jpg/640px-Roma_tomatoes.jpg",
        "description": "Tomate allongée parfaite pour les sauces",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Tomate Noire de Crimée",
        "name_latin": "Solanum lycopersicum 'Black Krim'",
        "variety": "Noire de Crimée",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Tomate_%28_Noire_de_Crim%C3%A9e%29_Cl_J_Weber01.jpg/640px-Tomate_%28_Noire_de_Crim%C3%A9e%29_Cl_J_Weber01.jpg",
        "description": "Tomate ancienne rouge foncé, saveur intense",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et profond",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Cornu des Andes",
        "name_latin": "Solanum lycopersicum 'Cornu des Andes'",
        "variety": "Cornu des Andes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.fermedesaintemarthe.com/cdn/shop/files/TOMATE-ANDINE-CORNUE-AB-ENSACHAGE-FDSM-71260575.jpg?v=1749033427&width=713",
        "description": "Tomate allongée pointue rouge vif, chair ferme peu de graines",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Buffalo",
        "name_latin": "Solanum lycopersicum 'Buffalo'",
        "variety": "Buffalo",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.labonnegraine.com/3702-large_default/gigantomo-f1.jpg",
        "description": "Grosse tomate lisse rouge parfaite pour farce",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien amendé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Ananas",
        "name_latin": "Solanum lycopersicum 'Pineapple'",
        "variety": "Ananas",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tomatensorte_Saveol_Ananas_02_%28fcm%29.jpg/640px-Tomatensorte_Saveol_Ananas_02_%28fcm%29.jpg",
        "description": "Grosse tomate bicolore jaune-rouge, saveur douce fruitée",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Saint-Pierre",
        "name_latin": "Solanum lycopersicum 'Saint-Pierre'",
        "variety": "Saint-Pierre",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.gardenseedsmarket.com/images/detailed/57/003613-16101564PA_spez_FMm.jpg",
        "description": "Tomate ronde rouge classique, très productive",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol ordinaire enrichi",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Green Zebra",
        "name_latin": "Solanum lycopersicum 'Green Zebra'",
        "variety": "Green Zebra",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Green_Zebra_Tomato_65.jpg/640px-Green_Zebra_Tomato_65.jpg",
        "description": "Tomate verte rayée, saveur acidulée unique",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # CAROTTES (2 variétés) - Photo générique carottes
    {
        "name_fr": "Carotte de Nantes",
        "name_latin": "Daucus carota 'Nantaise'",
        "variety": "Nantes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.graines-semences.com/1676/carotte-de-nantes-2-bio.jpg",
        "description": "Carotte cylindrique orange vif, croquante et sucrée",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier léger",
        "soil_type": "Sol sablonneux profond",
        "monthly_watering": "Juin: 2 fois par semaine"
    },
    {
        "name_fr": "Carotte de Colmar",
        "name_latin": "Daucus carota 'Colmar'",
        "variety": "Colmar",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://cdn.live.srag.cahosting.de/media/catalog/product/cache/1b8f60cb7c11172c9e8d369ea19e612a/k/a/ka50_shop_1759762239_1.jpg",
        "description": "Grosse carotte conique, excellente conservation",
        "difficulty": "Moyen",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol profond meuble",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },

    # SALADES (9 variétés) - Photo générique laitue/salade
    {
        "name_fr": "Batavia Blonde",
        "name_latin": "Lactuca sativa 'Batavia'",
        "variety": "Batavia Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://kokopelli-semences.fr/media/cache/shop_product_large_thumbnail/p3619-1.jpg",
        "description": "Salade croquante blonde résistante à la chaleur",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre en été",
        "watering": "Arrosage régulier délicat",
        "soil_type": "Sol frais et riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Batavia Rouge",
        "name_latin": "Lactuca sativa 'Batavia Rouge'",
        "variety": "Batavia Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.fermedesaintemarthe.com/cdn/shop/files/LAITUE-BATAVIA-ROUGE-GRENOBLOISE-AB-ENSACHAGE-FDSM-71201523.jpg",
        "description": "Salade croquante rouge-bronze, décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre en été",
        "watering": "Arrosage régulier délicat",
        "soil_type": "Sol frais et riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Romaine",
        "name_latin": "Lactuca sativa 'Romana'",
        "variety": "Romaine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://static.wixstatic.com/media/2418dc_c51c87a0592e42e0a79b5c1aee1ddfee~mv2.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/2418dc_c51c87a0592e42e0a79b5c1aee1ddfee~mv2.jpg",
        "description": "Salade allongée, feuilles croquantes",
        "difficulty": "Facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil léger",
        "watering": "Arrosage fréquent",
        "soil_type": "Sol riche en matière organique",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Feuille de Chêne Blonde",
        "name_latin": "Lactuca sativa 'Oak Leaf Blonde'",
        "variety": "Feuille de Chêne Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://terrabacchus.fr/wp-content/uploads/sites/25/2016/09/salade-feuille-de-chene-01-600-web.jpg",
        "description": "Feuilles découpées vertes, très décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Feuille de Chêne Rouge",
        "name_latin": "Lactuca sativa 'Oak Leaf Red'",
        "variety": "Feuille de Chêne Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://primeurdusud.fr/wp-content/uploads/2021/02/depositphotos_3488659-stock-photo-red-cabbage-lettuce-head-isolated.jpg",
        "description": "Feuilles découpées rouges, très décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Lollo Rossa",
        "name_latin": "Lactuca sativa 'Lollo Rossa'",
        "variety": "Lollo Rossa",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.organicseeds4you.com/11352-large_default/graines-laitue-salade-lollo-rossa.jpg",
        "description": "Salade italienne frisée rouge bordeaux",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil modéré",
        "watering": "Arrosage délicat",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Iceberg",
        "name_latin": "Lactuca sativa 'Iceberg'",
        "variety": "Iceberg",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://m.media-amazon.com/images/I/71yxDa6DBJL._AC_SX679_.jpg",
        "description": "Salade pommée croquante, très populaire",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol frais et fertile",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Sucrine",
        "name_latin": "Lactuca sativa 'Sucrine'",
        "variety": "Sucrine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://res.cloudinary.com/hv9ssmzrz/image/fetch/c_fill,f_auto,h_976,q_auto,w_1300/https://images-ca-1-0-1-eu.s3-eu-west-1.amazonaws.com/photos/original/1670/sucrine-produit-AdobeStock_81010152.jpeg",
        "description": "Petite romaine sucrée, croquante et tendre",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Roquette",
        "name_latin": "Eruca sativa",
        "variety": "Roquette",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://agrifournitures.fr/198695-large_default/roquette-cultivee-lunel-non-traite.jpg",
        "description": "Salade au goût piquant et poivré, croissance rapide",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage fréquent",
        "soil_type": "Sol léger",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },

    # COURGETTES (2 variétés)
    {
        "name_fr": "Courgette Verte",
        "name_latin": "Cucurbita pepo 'Green'",
        "variety": "Verte",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://agrifournitures.fr/249247-medium_default/courgette-diamant-f1-non-traite.jpg",
        "description": "Courgette verte classique très productive",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage abondant au pied",
        "soil_type": "Sol riche en humus",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },
    {
        "name_fr": "Courgette Ronde de Nice",
        "name_latin": "Cucurbita pepo 'Ronde de Nice'",
        "variety": "Ronde de Nice",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.millevarietesanciennes.org/wp-content/uploads/2024/01/Courgette_Ronde_Nice_carre-1024x1024.jpg",
        "description": "Courgette sphérique parfaite pour farcir",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage généreux",
        "soil_type": "Sol bien amendé",
        "monthly_watering": "Juin: 4 fois par semaine"
    },

    # RADIS (2 variétés)
    {
        "name_fr": "Radis 18 Jours",
        "name_latin": "Raphanus sativus '18 Jours'",
        "variety": "18 Jours",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.willemsefrance.fr/cdn/shop/files/HOR_100070_1_BK_1741358175316_675x.jpg?v=1745998449",
        "description": "Radis rouge rond, croissance très rapide",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage léger régulier",
        "soil_type": "Sol meuble et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Radis Noir",
        "name_latin": "Raphanus sativus 'Niger'",
        "variety": "Noir",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.academiedugout.fr/images/16379/1200-auto/radis-noir-copy.jpg?poix=50&poiy=50",
        "description": "Radis d'hiver à peau noire, saveur piquante",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver"],
        "sunlight": "Soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol profond",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },

    # FRAISES (3 variétés)
    {
        "name_fr": "Fraise Mara des Bois",
        "name_latin": "Fragaria × ananassa 'Mara des Bois'",
        "variety": "Mara des Bois",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQfVxCSAMapxjnw2F9oRP_kfJNvRzonhWAivsTZ6bP4ACdzz3vIbofdVFIc5azPf-W17aZ7OqjZpAYs-ttuPRB3PG93G_BY1HSxe0WTa9w",
        "description": "Fraise remontante au goût de fraise des bois",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol légèrement acide",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Fraise Gariguette",
        "name_latin": "Fragaria × ananassa 'Gariguette'",
        "variety": "Gariguette",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://www.georgesdelbard.com/pub/catalog/petits_fruits/fraises/.fraisier_gariguette_m.jpg",
        "description": "Fraise précoce allongée très parfumée",
        "difficulty": "Moyen",
        "growing_season": ["printemps"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Fraise Charlotte",
        "name_latin": "Fragaria × ananassa 'Charlotte'",
        "variety": "Charlotte",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://www.georgesdelbard.com/pub/catalog/petits_fruits/fraises/.fraisier_charlotte_m.jpg",
        "description": "Fraise remontante à chair ferme",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage au pied",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # FRAMBOISES (2 variétés)
    {
        "name_fr": "Framboise Meeker",
        "name_latin": "Rubus idaeus 'Meeker'",
        "variety": "Meeker",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Raspberries05.jpg/800px-Raspberries05.jpg",
        "description": "Framboise d'été rouge foncé, très parfumée",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol frais et humifère",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Framboise Autumn Bliss",
        "name_latin": "Rubus idaeus 'Autumn Bliss'",
        "variety": "Autumn Bliss",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Raspberries05.jpg/800px-Raspberries05.jpg",
        "description": "Framboise remontante productive",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol frais",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # AUTRES LÉGUMES & FRUITS
    {
        "name_fr": "Poivron Doux d'Espagne",
        "name_latin": "Capsicum annuum 'Spanish'",
        "variety": "Doux d'Espagne",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Green-Yellow-Red-Pepper-2009.jpg/800px-Green-Yellow-Red-Pepper-2009.jpg",
        "description": "Gros poivron carré rouge vif, doux et charnu",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil et chaleur",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Concombre Long Anglais",
        "name_latin": "Cucumis sativus 'Long English'",
        "variety": "Long Anglais",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/800px-ARS_cucumber.jpg",
        "description": "Concombre allongé à peau fine sans amertume",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage abondant",
        "soil_type": "Sol riche et frais",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },
    {
        "name_fr": "Aubergine de Barbentane",
        "name_latin": "Solanum melongena 'Barbentane'",
        "variety": "Barbentane",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/800px-Solanum_melongena_24_08_2012_%281%29.JPG",
        "description": "Aubergine allongée violette, chair fondante",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil et chaleur",
        "watering": "Arrosage régulier modéré",
        "soil_type": "Sol riche et chaud",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Haricot Vert Mangetout",
        "name_latin": "Phaseolus vulgaris 'Mangetout'",
        "variety": "Mangetout",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Haricot_vert_pongo.jpg/800px-Haricot_vert_pongo.jpg",
        "description": "Haricot vert fin sans fil, très tendre",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol léger",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Épinard Géant d'Hiver",
        "name_latin": "Spinacia oleracea 'Giant Winter'",
        "variety": "Géant d'Hiver",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.graines-baumaux.fr/66861-thickbox_default/epinard-geant-d-hiver.jpg",
        "description": "Épinard résistant au froid, grandes feuilles",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver", "printemps"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche en azote",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Courge Butternut",
        "name_latin": "Cucurbita moschata 'Butternut'",
        "variety": "Butternut",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://gardenchick.com/wp-content/uploads/2024/11/Butternut-squash.jpg",
        "description": "Courge en forme de poire, chair douce et beurrée",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Potimarron",
        "name_latin": "Cucurbita maxima 'Potimarron'",
        "variety": "Potimarron",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.graines-baumaux.fr/69636-thickbox_default/potimarron-red-kuri.jpg",
        "description": "Courge orange en forme de toupie, goût de châtaigne",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage espacé",
        "soil_type": "Sol riche et profond",
        "monthly_watering": "Juin: 2 fois par semaine"
    },

    # AGRUMES (3 variétés)
    {
        "name_fr": "Citronnier",
        "name_latin": "Citrus limon",
        "variety": "Citron",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Lemon.jpg/800px-Lemon.jpg",
        "description": "Agrume acide aux multiples usages culinaires",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier modéré",
        "soil_type": "Sol bien drainé légèrement acide",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Oranger",
        "name_latin": "Citrus sinensis",
        "variety": "Orange",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Orange-Fruit-Pieces.jpg/800px-Orange-Fruit-Pieces.jpg",
        "description": "Agrume sucré riche en vitamine C",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Clémentinier",
        "name_latin": "Citrus clementina",
        "variety": "Clémentine",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://www.leaderplant.com/media/catalog/product/c/l/clementine-mandarine-fortune7.jpg",
        "description": "Petit agrume doux et facile à éplucher",
        "difficulty": "Moyen",
        "growing_season": ["automne", "hiver"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol drainé",
        "monthly_watering": "Juin: 2 fois par semaine"
    },

    # LÉGUMINEUSES (1 variété)
    {
        "name_fr": "Pois Mangetout Nain de Grâce",
        "name_latin": "Pisum sativum 'Nain de Grâce'",
        "variety": "Nain de Grâce",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.graines-baumaux.fr/68151-thickbox_default/pois-mangetout-nain-de-grace.jpg",
        "description": "Pois à cosses plates tendres, variété naine précoce",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier modéré",
        "soil_type": "Sol frais et bien drainé",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },

    # ALLIACÉES (4 variétés)
    {
        "name_fr": "Poireau",
        "name_latin": "Allium porrum",
        "variety": "Poireau",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://static.pourdebon.com/images/500-370/pourdebon-image-bucket-prod/109f2725fdfb4409eb3e36528b2d308a.jpg",
        "description": "Légume au goût délicat, résistant au froid",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver", "printemps"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et profond",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Oignon Rouge de Toulouges",
        "name_latin": "Allium cepa 'Rouge de Toulouges'",
        "variety": "Rouge de Toulouges",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Red_onion.jpg/800px-Red_onion.jpg",
        "description": "Oignon rouge doux du Roussillon, excellente conservation",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol léger et bien drainé",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },
    {
        "name_fr": "Ail",
        "name_latin": "Allium sativum",
        "variety": "Ail",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Garlic.jpg/800px-Garlic.jpg",
        "description": "Condiment aux propriétés médicinales reconnues",
        "difficulty": "Très facile",
        "growing_season": ["automne", "hiver"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage très léger",
        "soil_type": "Sol léger et bien drainé",
        "monthly_watering": "Juin: 1 fois par semaine"
    },
    {
        "name_fr": "Échalote",
        "name_latin": "Allium ascalonicum",
        "variety": "Échalote",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Shallots_-_sliced_and_whole.jpg/800px-Shallots_-_sliced_and_whole.jpg",
        "description": "Petit bulbe au goût fin, indispensable en cuisine",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage léger",
        "soil_type": "Sol meuble et drainé",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },
    {
        "name_fr": "Oignon Blanc",
        "name_latin": "Allium cepa 'Blanc'",
        "variety": "Oignon Blanc",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/White_onions.jpg/800px-White_onions.jpg",
        "description": "Oignon blanc doux et croquant, récolte précoce",
        "difficulty": "Facile",
        "growing_season": ["printemps"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol fertile et drainé",
        "monthly_watering": "Juin: 2 fois par semaine"
    },
]