# Base de données complète des plantes avec variétés - URLs Wikipedia Commons
# 37 variétés avec photos génériques temporaires

PLANTS_DATABASE = [
    # TOMATES (10 variétés) - Photo générique tomates rouges
    {
        "name_fr": "Tomate Cœur de Bœuf",
        "name_latin": "Solanum lycopersicum 'Cœur de Bœuf'",
        "variety": "Cœur de Bœuf",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Coeur_de_boeuf_vraie.JPG/800px-Coeur_de_boeuf_vraie.JPG",
        "description": "Grosse tomate charnue en forme de cœur, très savoureuse",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil (8h minimum)",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Marmande",
        "name_latin": "Solanum lycopersicum 'Marmande'",
        "variety": "Marmande",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Tomates_Marmande.jpg/1280px-Tomates_Marmande.jpg",
        "description": "Tomate côtelée, chair ferme, parfaite pour les salades",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré régulier",
        "soil_type": "Sol riche en humus",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Tomate Cerise",
        "name_latin": "Solanum lycopersicum 'Cherry'",
        "variety": "Cerise",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tomates_cerises_Luc_Viatour.jpg/640px-Tomates_cerises_Luc_Viatour.jpg",
        "description": "Petites tomates sucrées, très productives",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Roma",
        "name_latin": "Solanum lycopersicum 'Roma'",
        "variety": "Roma",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Roma_tomatoes.jpg/640px-Roma_tomatoes.jpg",
        "description": "Tomate allongée parfaite pour les sauces",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Tomate Noire de Crimée",
        "name_latin": "Solanum lycopersicum 'Black Krim'",
        "variety": "Noire de Crimée",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Tomate_%28_Noire_de_Crim%C3%A9e%29_Cl_J_Weber01.jpg/640px-Tomate_%28_Noire_de_Crim%C3%A9e%29_Cl_J_Weber01.jpg",
        "description": "Tomate ancienne rouge foncé, saveur intense",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et profond",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Cornu des Andes",
        "name_latin": "Solanum lycopersicum 'Cornu des Andes'",
        "variety": "Cornu des Andes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.fermedesaintemarthe.com/cdn/shop/files/TOMATE-ANDINE-CORNUE-AB-ENSACHAGE-FDSM-71260575.jpg?v=1749033427&width=713",
        "description": "Tomate allongée pointue rouge vif, chair ferme peu de graines",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Buffalo",
        "name_latin": "Solanum lycopersicum 'Buffalo'",
        "variety": "Buffalo",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.labonnegraine.com/3702-large_default/gigantomo-f1.jpg",
        "description": "Grosse tomate lisse rouge parfaite pour farce",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien amendé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Ananas",
        "name_latin": "Solanum lycopersicum 'Pineapple'",
        "variety": "Ananas",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tomatensorte_Saveol_Ananas_02_%28fcm%29.jpg/640px-Tomatensorte_Saveol_Ananas_02_%28fcm%29.jpg",
        "description": "Grosse tomate bicolore jaune-rouge, saveur douce fruitée",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Saint-Pierre",
        "name_latin": "Solanum lycopersicum 'Saint-Pierre'",
        "variety": "Saint-Pierre",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.gardenseedsmarket.com/images/detailed/57/003613-16101564PA_spez_FMm.jpg",
        "description": "Tomate ronde rouge classique, très productive",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol ordinaire enrichi",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Green Zebra",
        "name_latin": "Solanum lycopersicum 'Green Zebra'",
        "variety": "Green Zebra",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Green_Zebra_Tomato_65.jpg/640px-Green_Zebra_Tomato_65.jpg",
        "description": "Tomate verte rayée, saveur acidulée unique",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # CAROTTES (2 variétés) - Photo générique carottes
    {
        "name_fr": "Carotte de Nantes",
        "name_latin": "Daucus carota 'Nantaise'",
        "variety": "Nantes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/800px-Vegetable-Carrot-Bundle-wStalks.jpg",
        "description": "Carotte cylindrique orange vif, croquante et sucrée",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier léger",
        "soil_type": "Sol sablonneux profond",
        "monthly_watering": "Juin: 2 fois par semaine"
    },
    {
        "name_fr": "Carotte de Colmar",
        "name_latin": "Daucus carota 'Colmar'",
        "variety": "Colmar",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/800px-Vegetable-Carrot-Bundle-wStalks.jpg",
        "description": "Grosse carotte conique, excellente conservation",
        "difficulty": "Moyen",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol profond meuble",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },

    # SALADES (9 variétés) - Photo générique laitue/salade
    {
        "name_fr": "Batavia Blonde",
        "name_latin": "Lactuca sativa 'Batavia'",
        "variety": "Batavia Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lactuca_sativa_var_capitata0.jpg/800px-Lactuca_sativa_var_capitata0.jpg",
        "description": "Salade croquante blonde résistante à la chaleur",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre en été",
        "watering": "Arrosage régulier délicat",
        "soil_type": "Sol frais et riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Batavia Rouge",
        "name_latin": "Lactuca sativa 'Batavia Rouge'",
        "variety": "Batavia Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://www.fermedesaintemarthe.com/cdn/shop/files/LAITUE-BATAVIA-ROUGE-GRENOBLOISE-AB-ENSACHAGE-FDSM-71201523.jpg",
        "description": "Salade croquante rouge-bronze, décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre en été",
        "watering": "Arrosage régulier délicat",
        "soil_type": "Sol frais et riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Romaine",
        "name_latin": "Lactuca sativa 'Romana'",
        "variety": "Romaine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://static.wixstatic.com/media/2418dc_c51c87a0592e42e0a79b5c1aee1ddfee~mv2.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/2418dc_c51c87a0592e42e0a79b5c1aee1ddfee~mv2.jpg",
        "description": "Salade allongée, feuilles croquantes",
        "difficulty": "Facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil léger",
        "watering": "Arrosage fréquent",
        "soil_type": "Sol riche en matière organique",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Feuille de Chêne Blonde",
        "name_latin": "Lactuca sativa 'Oak Leaf Blonde'",
        "variety": "Feuille de Chêne Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lactuca_sativa_var_capitata0.jpg/800px-Lactuca_sativa_var_capitata0.jpg",
        "description": "Feuilles découpées vertes, très décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Feuille de Chêne Rouge",
        "name_latin": "Lactuca sativa 'Oak Leaf Red'",
        "variety": "Feuille de Chêne Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lactuca_sativa_var_capitata0.jpg/800px-Lactuca_sativa_var_capitata0.jpg",
        "description": "Feuilles découpées rouges, très décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Lollo Rossa",
        "name_latin": "Lactuca sativa 'Lollo Rossa'",
        "variety": "Lollo Rossa",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lactuca_sativa_var_capitata0.jpg/800px-Lactuca_sativa_var_capitata0.jpg",
        "description": "Salade italienne frisée rouge bordeaux",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil modéré",
        "watering": "Arrosage délicat",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Iceberg",
        "name_latin": "Lactuca sativa 'Iceberg'",
        "variety": "Iceberg",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lactuca_sativa_var_capitata0.jpg/800px-Lactuca_sativa_var_capitata0.jpg",
        "description": "Salade pommée croquante, très populaire",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol frais et fertile",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Sucrine",
        "name_latin": "Lactuca sativa 'Sucrine'",
        "variety": "Sucrine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lactuca_sativa_var_capitata0.jpg/800px-Lactuca_sativa_var_capitata0.jpg",
        "description": "Petite romaine sucrée, croquante et tendre",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Roquette",
        "name_latin": "Eruca sativa",
        "variety": "Roquette",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Lactuca_sativa_var_capitata0.jpg/800px-Lactuca_sativa_var_capitata0.jpg",
        "description": "Salade au goût piquant et poivré, croissance rapide",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage fréquent",
        "soil_type": "Sol léger",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },

    # COURGETTES (2 variétés)
    {
        "name_fr": "Courgette Verte",
        "name_latin": "Cucurbita pepo 'Green'",
        "variety": "Verte",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Zucchini_in_bloom.jpg/800px-Zucchini_in_bloom.jpg",
        "description": "Courgette verte classique très productive",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage abondant au pied",
        "soil_type": "Sol riche en humus",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },
    {
        "name_fr": "Courgette Ronde de Nice",
        "name_latin": "Cucurbita pepo 'Ronde de Nice'",
        "variety": "Ronde de Nice",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Zucchini_in_bloom.jpg/800px-Zucchini_in_bloom.jpg",
        "description": "Courgette sphérique parfaite pour farcir",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage généreux",
        "soil_type": "Sol bien amendé",
        "monthly_watering": "Juin: 4 fois par semaine"
    },

    # RADIS (2 variétés)
    {
        "name_fr": "Radis 18 Jours",
        "name_latin": "Raphanus sativus '18 Jours'",
        "variety": "18 Jours",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Radishes_on_a_bench.jpg/800px-Radishes_on_a_bench.jpg",
        "description": "Radis rouge rond, croissance très rapide",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage léger régulier",
        "soil_type": "Sol meuble et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Radis Noir",
        "name_latin": "Raphanus sativus 'Niger'",
        "variety": "Noir",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Radishes_on_a_bench.jpg/800px-Radishes_on_a_bench.jpg",
        "description": "Radis d'hiver à peau noire, saveur piquante",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver"],
        "sunlight": "Soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol profond",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },

    # FRAISES (3 variétés)
    {
        "name_fr": "Fraise Mara des Bois",
        "name_latin": "Fragaria × ananassa 'Mara des Bois'",
        "variety": "Mara des Bois",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PerfectStrawberry.jpg/800px-PerfectStrawberry.jpg",
        "description": "Fraise remontante au goût de fraise des bois",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol légèrement acide",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Fraise Gariguette",
        "name_latin": "Fragaria × ananassa 'Gariguette'",
        "variety": "Gariguette",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PerfectStrawberry.jpg/800px-PerfectStrawberry.jpg",
        "description": "Fraise précoce allongée très parfumée",
        "difficulty": "Moyen",
        "growing_season": ["printemps"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Fraise Charlotte",
        "name_latin": "Fragaria × ananassa 'Charlotte'",
        "variety": "Charlotte",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PerfectStrawberry.jpg/800px-PerfectStrawberry.jpg",
        "description": "Fraise remontante à chair ferme",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage au pied",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # FRAMBOISES (2 variétés)
    {
        "name_fr": "Framboise Meeker",
        "name_latin": "Rubus idaeus 'Meeker'",
        "variety": "Meeker",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Raspberries05.jpg/800px-Raspberries05.jpg",
        "description": "Framboise d'été rouge foncé, très parfumée",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol frais et humifère",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Framboise Autumn Bliss",
        "name_latin": "Rubus idaeus 'Autumn Bliss'",
        "variety": "Autumn Bliss",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Raspberries05.jpg/800px-Raspberries05.jpg",
        "description": "Framboise remontante productive",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol frais",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # AUTRES LÉGUMES & FRUITS
    {
        "name_fr": "Poivron Doux d'Espagne",
        "name_latin": "Capsicum annuum 'Spanish'",
        "variety": "Doux d'Espagne",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Green-Yellow-Red-Pepper-2009.jpg/800px-Green-Yellow-Red-Pepper-2009.jpg",
        "description": "Gros poivron carré rouge vif, doux et charnu",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil et chaleur",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Concombre Long Anglais",
        "name_latin": "Cucumis sativus 'Long English'",
        "variety": "Long Anglais",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/800px-ARS_cucumber.jpg",
        "description": "Concombre allongé à peau fine sans amertume",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage abondant",
        "soil_type": "Sol riche et frais",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },
    {
        "name_fr": "Aubergine de Barbentane",
        "name_latin": "Solanum melongena 'Barbentane'",
        "variety": "Barbentane",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/800px-Solanum_melongena_24_08_2012_%281%29.JPG",
        "description": "Aubergine allongée violette, chair fondante",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil et chaleur",
        "watering": "Arrosage régulier modéré",
        "soil_type": "Sol riche et chaud",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Haricot Vert Mangetout",
        "name_latin": "Phaseolus vulgaris 'Mangetout'",
        "variety": "Mangetout",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Haricot_vert_pongo.jpg/800px-Haricot_vert_pongo.jpg",
        "description": "Haricot vert fin sans fil, très tendre",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol léger",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Épinard Géant d'Hiver",
        "name_latin": "Spinacia oleracea 'Giant Winter'",
        "variety": "Géant d'Hiver",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Spinach_bunch.jpg/800px-Spinach_bunch.jpg",
        "description": "Épinard résistant au froid, grandes feuilles",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver", "printemps"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche en azote",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Courge Butternut",
        "name_latin": "Cucurbita moschata 'Butternut'",
        "variety": "Butternut",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Butternut_squash_and_cross_section.jpg/800px-Butternut_squash_and_cross_section.jpg",
        "description": "Courge en forme de poire, chair douce et beurrée",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Potimarron",
        "name_latin": "Cucurbita maxima 'Potimarron'",
        "variety": "Potimarron",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Potimarron.JPG/800px-Potimarron.JPG",
        "description": "Courge orange en forme de toupie, goût de châtaigne",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage espacé",
        "soil_type": "Sol riche et profond",
        "monthly_watering": "Juin: 2 fois par semaine"
    },
]