# Base de données complète des plantes avec variétés - URLs vérifiées
# 42 variétés avec photos correctes

PLANTS_DATABASE = [
    # TOMATES (10 variétés)
    {
        "name_fr": "Tomate Cœur de Bœuf",
        "name_latin": "Solanum lycopersicum 'Cœur de Bœuf'",
        "variety": "Cœur de Bœuf",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Grosse tomate charnue en forme de cœur, très savoureuse",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil (8h minimum)",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et bien drainé",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Marmande",
        "name_latin": "Solanum lycopersicum 'Marmande'",
        "variety": "Marmande",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Tomate côtelée, chair ferme, parfaite pour les salades",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré régulier",
        "soil_type": "Sol riche en humus",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Tomate Cerise",
        "name_latin": "Solanum lycopersicum 'Cherry'",
        "variety": "Cerise",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Petites tomates sucrées, très productives",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Roma",
        "name_latin": "Solanum lycopersicum 'Roma'",
        "variety": "Roma",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Tomate allongée parfaite pour les sauces",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Tomate Noire de Crimée",
        "name_latin": "Solanum lycopersicum 'Black Krim'",
        "variety": "Noire de Crimée",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Tomate ancienne rouge foncé, saveur intense",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et profond",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Cornu des Andes",
        "name_latin": "Solanum lycopersicum 'Cornu des Andes'",
        "variety": "Cornu des Andes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Tomate allongée pointue rouge vif, chair ferme peu de graines",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Buffalo",
        "name_latin": "Solanum lycopersicum 'Buffalo'",
        "variety": "Buffalo",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Grosse tomate lisse rouge parfaite pour farce",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien amendé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Ananas",
        "name_latin": "Solanum lycopersicum 'Pineapple'",
        "variety": "Ananas",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Grosse tomate bicolore jaune-rouge, saveur douce fruitée",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Tomate Saint-Pierre",
        "name_latin": "Solanum lycopersicum 'Saint-Pierre'",
        "variety": "Saint-Pierre",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Tomate ronde rouge classique, très productive",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol ordinaire enrichi",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Tomate Green Zebra",
        "name_latin": "Solanum lycopersicum 'Green Zebra'",
        "variety": "Green Zebra",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?w=400&q=80",
        "description": "Tomate verte rayée, saveur acidulée unique",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # CAROTTES (2 variétés)
    {
        "name_fr": "Carotte de Nantes",
        "name_latin": "Daucus carota 'Nantaise'",
        "variety": "Nantes",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg?w=400&q=80",
        "description": "Carotte cylindrique orange vif, croquante et sucrée",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier léger",
        "soil_type": "Sol sablonneux profond",
        "monthly_watering": "Juin: 2 fois par semaine"
    },
    {
        "name_fr": "Carotte de Colmar",
        "name_latin": "Daucus carota 'Colmar'",
        "variety": "Colmar",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/65174/pexels-photo-65174.jpeg?w=400&q=80",
        "description": "Grosse carotte conique, excellente conservation",
        "difficulty": "Moyen",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol profond meuble",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },

    # SALADES (9 variétés)
    {
        "name_fr": "Batavia Blonde",
        "name_latin": "Lactuca sativa 'Batavia'",
        "variety": "Batavia Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Salade croquante blonde résistante à la chaleur",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre en été",
        "watering": "Arrosage régulier délicat",
        "soil_type": "Sol frais et riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Batavia Rouge",
        "name_latin": "Lactuca sativa 'Batavia Rouge'",
        "variety": "Batavia Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Salade croquante rouge-bronze, décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre en été",
        "watering": "Arrosage régulier délicat",
        "soil_type": "Sol frais et riche",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Romaine",
        "name_latin": "Lactuca sativa 'Romana'",
        "variety": "Romaine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Salade allongée, feuilles croquantes",
        "difficulty": "Facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil léger",
        "watering": "Arrosage fréquent",
        "soil_type": "Sol riche en matière organique",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Feuille de Chêne Blonde",
        "name_latin": "Lactuca sativa 'Oak Leaf Blonde'",
        "variety": "Feuille de Chêne Blonde",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Feuilles découpées vertes, très décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Feuille de Chêne Rouge",
        "name_latin": "Lactuca sativa 'Oak Leaf Red'",
        "variety": "Feuille de Chêne Rouge",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Feuilles découpées rouges, très décorative",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol léger et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Lollo Rossa",
        "name_latin": "Lactuca sativa 'Lollo Rossa'",
        "variety": "Lollo Rossa",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Salade italienne frisée rouge bordeaux",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil modéré",
        "watering": "Arrosage délicat",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Iceberg",
        "name_latin": "Lactuca sativa 'Iceberg'",
        "variety": "Iceberg",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Salade pommée croquante, très populaire",
        "difficulty": "Moyen",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol frais et fertile",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Sucrine",
        "name_latin": "Lactuca sativa 'Sucrine'",
        "variety": "Sucrine",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Petite romaine sucrée, croquante et tendre",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Roquette",
        "name_latin": "Eruca sativa",
        "variety": "Roquette",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg?w=400&q=80",
        "description": "Salade au goût piquant et poivré, croissance rapide",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage fréquent",
        "soil_type": "Sol léger",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },

    # COURGETTES (2 variétés)
    {
        "name_fr": "Courgette Verte",
        "name_latin": "Cucurbita pepo 'Green'",
        "variety": "Verte",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/47347/squash-fruit-healthy-food-47347.jpeg?w=400&q=80",
        "description": "Courgette verte classique très productive",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage abondant au pied",
        "soil_type": "Sol riche en humus",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },
    {
        "name_fr": "Courgette Ronde de Nice",
        "name_latin": "Cucurbita pepo 'Ronde de Nice'",
        "variety": "Ronde de Nice",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/47347/squash-fruit-healthy-food-47347.jpeg?w=400&q=80",
        "description": "Courgette sphérique parfaite pour farcir",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage généreux",
        "soil_type": "Sol bien amendé",
        "monthly_watering": "Juin: 4 fois par semaine"
    },

    # RADIS (2 variétés)
    {
        "name_fr": "Radis 18 Jours",
        "name_latin": "Raphanus sativus '18 Jours'",
        "variety": "18 Jours",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/51360/radish-vegetables-food-fresh-51360.jpeg?w=400&q=80",
        "description": "Radis rouge rond, croissance très rapide",
        "difficulty": "Très facile",
        "growing_season": ["printemps", "automne"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage léger régulier",
        "soil_type": "Sol meuble et frais",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Radis Noir",
        "name_latin": "Raphanus sativus 'Niger'",
        "variety": "Noir",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/51360/radish-vegetables-food-fresh-51360.jpeg?w=400&q=80",
        "description": "Radis d'hiver à peau noire, saveur piquante",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver"],
        "sunlight": "Soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol profond",
        "monthly_watering": "Juin: 1-2 fois par semaine"
    },

    # FRAISES (3 variétés)
    {
        "name_fr": "Fraise Mara des Bois",
        "name_latin": "Fragaria × ananassa 'Mara des Bois'",
        "variety": "Mara des Bois",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://images.pexels.com/photos/46174/strawberries-berries-fruit-freshness-46174.jpeg?w=400&q=80",
        "description": "Fraise remontante au goût de fraise des bois",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier au pied",
        "soil_type": "Sol légèrement acide",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Fraise Gariguette",
        "name_latin": "Fragaria × ananassa 'Gariguette'",
        "variety": "Gariguette",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://images.pexels.com/photos/46174/strawberries-berries-fruit-freshness-46174.jpeg?w=400&q=80",
        "description": "Fraise précoce allongée très parfumée",
        "difficulty": "Moyen",
        "growing_season": ["printemps"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 4 fois par semaine"
    },
    {
        "name_fr": "Fraise Charlotte",
        "name_latin": "Fragaria × ananassa 'Charlotte'",
        "variety": "Charlotte",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://images.pexels.com/photos/46174/strawberries-berries-fruit-freshness-46174.jpeg?w=400&q=80",
        "description": "Fraise remontante à chair ferme",
        "difficulty": "Facile",
        "growing_season": ["printemps", "été", "automne"],
        "sunlight": "Soleil",
        "watering": "Arrosage au pied",
        "soil_type": "Sol bien drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # FRAMBOISES (2 variétés)
    {
        "name_fr": "Framboise Meeker",
        "name_latin": "Rubus idaeus 'Meeker'",
        "variety": "Meeker",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?w=400&q=80",
        "description": "Framboise d'été rouge foncé, très parfumée",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Soleil à mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol frais et humifère",
        "monthly_watering": "Juin: 3-4 fois par semaine"
    },
    {
        "name_fr": "Framboise Autumn Bliss",
        "name_latin": "Rubus idaeus 'Autumn Bliss'",
        "variety": "Autumn Bliss",
        "category": "potager",
        "subcategory": "fruits",
        "image_url": "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?w=400&q=80",
        "description": "Framboise remontante productive",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage modéré",
        "soil_type": "Sol frais",
        "monthly_watering": "Juin: 3 fois par semaine"
    },

    # AUTRES LÉGUMES & FRUITS
    {
        "name_fr": "Poivron Doux d'Espagne",
        "name_latin": "Capsicum annuum 'Spanish'",
        "variety": "Doux d'Espagne",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/594137/pexels-photo-594137.jpeg?w=400&q=80",
        "description": "Gros poivron carré rouge vif, doux et charnu",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil et chaleur",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche et drainé",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Concombre Long Anglais",
        "name_latin": "Cucumis sativus 'Long English'",
        "variety": "Long Anglais",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/37528/cucumber-salad-food-healthy-37528.jpeg?w=400&q=80",
        "description": "Concombre allongé à peau fine sans amertume",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage abondant",
        "soil_type": "Sol riche et frais",
        "monthly_watering": "Juin: 4-5 fois par semaine"
    },
    {
        "name_fr": "Aubergine de Barbentane",
        "name_latin": "Solanum melongena 'Barbentane'",
        "variety": "Barbentane",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/321551/pexels-photo-321551.jpeg?w=400&q=80",
        "description": "Aubergine allongée violette, chair fondante",
        "difficulty": "Moyen",
        "growing_season": ["été"],
        "sunlight": "Plein soleil et chaleur",
        "watering": "Arrosage régulier modéré",
        "soil_type": "Sol riche et chaud",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Haricot Vert Mangetout",
        "name_latin": "Phaseolus vulgaris 'Mangetout'",
        "variety": "Mangetout",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/1359326/pexels-photo-1359326.jpeg?w=400&q=80",
        "description": "Haricot vert fin sans fil, très tendre",
        "difficulty": "Facile",
        "growing_season": ["été"],
        "sunlight": "Soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol léger",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Épinard Géant d'Hiver",
        "name_latin": "Spinacia oleracea 'Giant Winter'",
        "variety": "Géant d'Hiver",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/2255925/pexels-photo-2255925.jpeg?w=400&q=80",
        "description": "Épinard résistant au froid, grandes feuilles",
        "difficulty": "Facile",
        "growing_season": ["automne", "hiver", "printemps"],
        "sunlight": "Mi-ombre",
        "watering": "Arrosage régulier",
        "soil_type": "Sol riche en azote",
        "monthly_watering": "Juin: 3 fois par semaine"
    },
    {
        "name_fr": "Courge Butternut",
        "name_latin": "Cucurbita moschata 'Butternut'",
        "variety": "Butternut",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/4022090/pexels-photo-4022090.jpeg?w=400&q=80",
        "description": "Courge en forme de poire, chair douce et beurrée",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage modéré",
        "soil_type": "Sol riche",
        "monthly_watering": "Juin: 2-3 fois par semaine"
    },
    {
        "name_fr": "Potimarron",
        "name_latin": "Cucurbita maxima 'Potimarron'",
        "variety": "Potimarron",
        "category": "potager",
        "subcategory": "legumes",
        "image_url": "https://images.pexels.com/photos/6140489/pexels-photo-6140489.jpeg?w=400&q=80",
        "description": "Courge orange en forme de toupie, goût de châtaigne",
        "difficulty": "Facile",
        "growing_season": ["été", "automne"],
        "sunlight": "Plein soleil",
        "watering": "Arrosage espacé",
        "soil_type": "Sol riche et profond",
        "monthly_watering": "Juin: 2 fois par semaine"
    },
]